## 本地数据集参数
# ct_root_path: data/ct_mask
# dataset_path: data/detection_test
# dataset_images_path: data/detection_test/images
# dataset_masks_path: data/detection_test/masks
# dataset_json_path: data/detection_test/detection_data.json

projection_parameter:
  sdr: 500
  height: 2000
  specific_height_list: {"chen_jing": 3000, "chen_min_hua": 2500, "hang_hui_fang": 1000, "wang_xing_di": 1000, "xu_ye": 3000, "zhang_jian_min": 2500, "zhou_yuan_ying": 1000}
  delx: 0.25
  threshold: 0
  AP_num_samples: 1
  LA_num_samples: 1
  AP_rot_range_list: [[75, 105], [-180, 180], [165, 195]]
  AP_trans_range_list: [[-30, 30], [-30, 30], [-30, 30]]
  LA_rot_range_list: [[75, 105], [-180, 180], [75, 105]]
  LA_trans_range_list: [[-30, 30], [-30, 30], [-30, 30]]
  AP_bbox_label_type: small
  LA_bbox_label_type: big
  min_bbox_percentage_of_height: 0.05


# vis_parameter:
#   is_vis: True
#   vis_save_path: data/detection_test/bbox_vis
#   rotation_bbox_vis_save_path: data/detection_test/rotation_bbox_vis # 旋转框可视化


# verse数据集参数
# ct_root_path: data/test
# dataset_path: data/test_drr
# dataset_images_path: data/test_drr/images
# dataset_masks_path: data/test_drr/masks
# dataset_json_path: data/test_drr/detection_data.json

# projection_parameter:
#   sdr: 500
#   height: 512
#   specific_height_list: {}
#   delx: 1
#   threshold: 0
#   AP_num_samples: 2
#   LA_num_samples: 2
#   AP_rot_range_list: [[75, 105], [165, 195], [165, 195]]
#   AP_trans_range_list: [[-30, 30], [-30, 30], [-30, 30]]
#   LA_rot_range_list: [[75, 105], [165, 195], [75, 105]]
#   LA_trans_range_list: [[-30, 30], [-30, 30], [-30, 30]]
#   # AP_rot_range_list: [[90, 90], [180, 180], [180, 180]]
#   # AP_trans_range_list: [[0, 0], [0, 0], [0, 0]]
#   # LA_rot_range_list: [[90, 90], [180, 180], [90, 90]]
#   # LA_trans_range_list: [[0, 0], [0, 0], [0, 0]]
#   AP_bbox_label_type: big
#   LA_bbox_label_type: big
#   min_bbox_percentage_of_height: 0.05


# vis_parameter:
#   is_vis: True
#   vis_save_path: data/test_drr/bbox_vis
#   rotation_bbox_vis_save_path: data/test_drr/rotation_bbox_vis # 旋转框可视化


# deformity数据集参数
ct_root_path: data/deformity
dataset_path: data/deformity_drr
dataset_images_path: data/deformity_drr/images
dataset_masks_path: data/deformity_drr/masks
dataset_json_path: data/deformity_drr/detection_data.json

projection_parameter:
  sdr: 500
  height: 512
  specific_height_list: {}
  delx: 1
  threshold: 0
  AP_num_samples: 1
  LA_num_samples: 1
  # AP_rot_range_list: [[75, 105], [165, 195], [165, 195]]
  # AP_trans_range_list: [[-30, 30], [-30, 30], [-30, 30]]
  # LA_rot_range_list: [[75, 105], [165, 195], [75, 105]]
  # LA_trans_range_list: [[-30, 30], [-30, 30], [-30, 30]]
  AP_rot_range_list: [[90, 90], [180, 180], [180, 180]]
  AP_trans_range_list: [[0, 0], [0, 0], [0, 0]]
  LA_rot_range_list: [[90, 90], [180, 180], [90, 90]]
  LA_trans_range_list: [[0, 0], [0, 0], [0, 0]]
  AP_bbox_label_type: big
  LA_bbox_label_type: big
  min_bbox_percentage_of_height: 0.05


vis_parameter:
  is_vis: True
  vis_save_path: data/deformity_drr/bbox_vis
  rotation_bbox_vis_save_path: data/deformity_drr/rotation_bbox_vis # 旋转框可视化