data_root_path: data
ct_mask_path: data/Local_fracture
dataset_save_root_folder_name: test
APorLA_orientation: all # AP LA all
mask_categories: ["body"] # whole body pedicle other
nii_preproess: False
has_pedicle: True

# 3D to 2d parameter
projection_parameter:
  sdr: 500
  height: 1000
  specific_height_list: {"hang_hui_fang": 500, "ji_lai_ying": 500, "liu_xin": 500, "rui_guo_fa": 500, "teng_jin_fa": 500, "wang_xing_di": 500, "yan_gen_ying": 500, "zhou_yuan_ying": 500}
  delx: 0.5
  threshold: 0
  AP_num_samples: 15
  LA_num_samples: 15
  AP_rot_range_list : [[85, 95], [165, 195], [175, 185]]
  AP_trans_range_list : [[-20, 20], [-20, 20], [-20, 20]]
  LA_rot_range_list: [[85, 95], [165, 195], [85, 95]]
  LA_trans_range_list: [[-20, 20], [-20, 20], [-20, 20]]
  min_bbox_percentage_of_height: 0.05
  
# Mode of clipping
cut_parameter:
  cut_mode: mask_center # mask_center detection_bbox_center
  detection_result_json_path: data/test/all/detection_result/bbox.json
  run_object_detection: False
  AP_expand_coefficient: 1.1
  LA_expand_coefficient: 1.1
  Minimum_width_relative_to_the_image: 0.15
  Minimum_height_relative_to_the_image: 0.15

vis_parameter:
  is_vis: True