data_root_path: data
ct_mask_path: data/ct_mask
dataset_save_root_folder_name: detection_dataset
APorLA_orientation: all # AP LA all
mask_categories: ["body"] # whole body pedicle other
nii_preproess: False
has_pedicle: True

# 3D to 2d parameter
projection_parameter:
  sdr: 500
  height: 512
  specific_height_list: {"hang_hui_fang": 512, "ji_lai_ying": 512, "liu_xin": 512, "rui_guo_fa": 512, "teng_jin_fa": 512, "wang_xing_di": 512, "yan_gen_ying": 512, "zhou_yuan_ying": 512}
  delx: 1
  threshold: 0
  AP_num_samples: 20
  LA_num_samples: 20
  AP_rot_range_list : [[90, 90], [180, 180], [165, 195]]
  AP_trans_range_list : [[-30, 30], [-30, 30], [-30, 30]]
  LA_rot_range_list: [[90, 90], [180, 180], [75, 105]]
  LA_trans_range_list: [[-30, 30], [-30, 30], [-30, 30]]
  min_bbox_percentage_of_height: 0.05
  
# Mode of clipping
cut_parameter:
  cut_mode: mask_center # mask_center detection_bbox_center
  detection_result_json_path: data/verse2020_test_segmentation_dataset/all/detection_result/bbox.json
  run_object_detection: False
  AP_expand_coefficient: 1.1
  LA_expand_coefficient: 1.1
  Minimum_width_relative_to_the_image: 0.10
  Minimum_height_relative_to_the_image: 0.10

vis_parameter:
  is_vis: True